# Header
menu:
  主页: /
  归档: /archives
#  分类: /categories
  日常笔记: /notes
  图片压缩: https://tiven.cn/service/image/compress
  Txt2Excel: https://tiven.cn/service/tools/txt-to-excel
  留言: /comments
  关于: /about
#  标签: /tag
#  标签云: /tagcloud
rss: /atom.xml
sitemap: /sitemap.xml || sitemap

# Content
#  查看更多 Read More
excerpt_link: 阅读全文
fancybox: true

# Sidebar
# 导航栏位置
sidebar: right
widgets:
- recent_posts
# 归类
- category
# 标签
#- tag
# 标签云
#- tagcloud
- archive
# 浏览量统计
## - popular_posts
# 友情链接
#- links

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
 - category
 - tagcloud
 - archive

# widget behavior
# 依据什么来分类（此处以月份来分类）
archive_type: 'monthly'
# 显示当前分类的博客条数
show_count: true

# Miscellaneous
# ico图片
favicon: /favicon.ico
google_analytics:
twitter:
google_plus:
fb_admins:
fb_app_id:


# 是否开启打赏功能
#donate: true
# 打赏文案
#donate_message: 欣赏此文？求鼓励，求支持！

# 站内文章搜索
#local_search:
#  enable: true

# 文章字数统计及阅读时常功能
post_wordcount:
  item_text: true
  wordcount: true #单篇文章字数
  min2read: true #单篇阅读时长
  totalcount: true #站点总字数
  separated_meta: true

# valine comment system. https://valine.js.org
valine:
  enable: true # if you want use valine,please set this value is true
  appId: r1dLByknj47xfH43HURm6E8y-gzGzoHsz # leancloud application app id
  appKey: bIhGLvNYin6d2N6gmQuMTFXE # leancloud application app key
  notify: true # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
  verify: true # valine verify code (true/false)
  pageSize: 10 # comment list page size
  avatar: wavatar # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: Biu Biu Biu 〜 # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info